<a href="https://colab.research.google.com/github/AmirJlr/RecSys/blob/master/LLM-based/02_BookRecLLM_Engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -qU langchain langchain-community langchain-google-genai langchain-chroma transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 90.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 61.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 59.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 72.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 92.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.5/118.5 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.2/196.2 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.2/71.2 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.8/459.8 kB 30.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 96.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.1/453.1 kB 28.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 6.0 MB/s eta 0:00:00
  Building wheel for pypika (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-generativeai 0.8.5 requires google-ai-generativelanguage==0.6.15, but you have google-ai-generativelanguage 0.6.18 which is incompatible.

In [ ]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma

In [ ]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')
os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')

### Or use python-dotenv

In [ ]:
import pandas as pd

books = pd.read_csv("/content/drive/MyDrive/recommender_systems/LLM/books_cleaned.csv")

In [ ]:
books.tagged_description.to_csv("tagged_description.txt", sep="\n", index=False, header=False)

In [ ]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator='\n')

documents = text_splitter.split_documents(raw_documents)

Streaming output truncated to the last 5000 lines.
WARNING:langchain_text_splitters.base:Created a chunk of size 1483, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 221, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1135, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 722, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 668, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 765, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 606, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 570, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 965, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 857, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1032, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 367, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 495, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 652, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 348, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 525, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1015, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 970, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 204, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 688, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 544, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 207, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 376, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 564, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 715, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 749, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 324, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 241, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 723, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 704, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1912, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 395, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 622, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 559, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 556, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 386, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 229, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 425, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 418, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 284, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 166, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 624, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2616, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1580, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 389, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 994, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 847, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 263, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 336, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1530, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 213, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 291, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2030, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 396, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1619, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 698, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 822, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 354, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 195, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 508, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 663, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1282, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 260, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 215, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1277, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1056, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 269, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 177, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 225, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 222, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 784, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 613, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 163, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 757, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 289, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 963, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 232, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 786, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 648, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 984, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 193, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1163, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 253, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 203, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1058, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 246, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 875, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 817, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 755, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 569, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 628, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 620, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 621, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1084, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2762, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1033, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 758, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 773, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 634, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1010, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 492, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 795, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 699, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 372, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1224, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 223, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 345, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 657, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 199, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 767, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 553, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 233, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 590, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 238, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 299, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 726, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1805, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 684, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 739, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 236, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 449, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 472, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 922, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 162, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 967, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 477, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 645, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 676, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 211, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 760, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 796, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 679, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 927, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 772, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 770, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 335, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 649, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1771, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 534, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 824, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 261, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 599, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 486, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 554, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 491, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 844, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 876, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 0

In [ ]:
db_books = Chroma.from_documents(
    documents, embedding=GoogleGenerativeAIEmbeddings(model="models/embedding-001")
)

ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

In [ ]:
query = "A book about football"

recs = db_books.similarity_search(query, k=3)
recs

ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event CollectionQueryEvent: capture() takes 1 positional argument but 3 were given

[Document(id='594ef880-123e-4dde-b09a-5cf67cf6bd52', metadata={'source': 'tagged_description.txt'}, page_content='9781573226882 An autobiographical memoir by a humorous British author and obsessed soccer fan captures the intensity of a sports fan who measures his life in seasons rather than years'),
 Document(id='13d47a35-6d29-4cab-882f-bcf7087df586', metadata={'source': 'tagged_description.txt'}, page_content="9781406934854 This is a reproduction of the original artefact. Generally these books are created from careful scans of the original. This allows us to preserve the book accurately and present it in the way the author intended. Since the original versions are generally quite old, there may occasionally be certain imperfections within these reproductions. We're happy to make these classics available again for future generations to enjoy!"),
 Document(id='9f69f725-95bd-4652-8be6-07a36ab1ebeb', metadata={'source': 'tagged_description.txt'}, page_content="9781406904833 This is a reproduction of the original artefact. Generally these books are created from careful scans of the original. This allows us to preserve the book accurately and present it in the way the author intended. Since the original versions are generally quite old, there may occasionally be certain imperfections within these reproductions. We're happy to make these classics available again for future generations to enjoy!")]

In [ ]:
recs[2]

Document(id='9f69f725-95bd-4652-8be6-07a36ab1ebeb', metadata={'source': 'tagged_description.txt'}, page_content="9781406904833 This is a reproduction of the original artefact. Generally these books are created from careful scans of the original. This allows us to preserve the book accurately and present it in the way the author intended. Since the original versions are generally quite old, there may occasionally be certain imperfections within these reproductions. We're happy to make these classics available again for future generations to enjoy!")

In [ ]:
books.head(1)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...

In [ ]:
books[books['isbn13'] == int(recs[0].page_content.split(" ")[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
4700,9781573226882,1573226882,Fever Pitch,Nick Hornby,Biography & Autobiography,http://books.google.com/books/content?id=v5TO8...,An autobiographical memoir by a humorous Briti...,1998.0,3.73,247.0,27781.0,Fever Pitch,9781573226882 An autobiographical memoir by a ...

In [ ]:
def retrieve_semantic_recommendation(dataframe, db, query, num_recs):
    recs = db.similarity_search(query, k=num_recs)

    book_list = []
    for i in range(len(recs)):
        book_list.append(int(recs[i].page_content.strip('"').split(" ")[0]))

    return dataframe[dataframe["isbn13"].isin(book_list)]

In [ ]:
retrieve_semantic_recommendation(books, db_books, "A book about football", 5)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
4461,9781406904833,140690483X,Nöddebo Parsonage,Bentley,NaN,http://books.google.com/books/content?id=OFJyy...,This is a reproduction of the original artefac...,2019.0,4.32,224.0,8206.0,Nöddebo Parsonage: A Story of Country Life in ...,9781406904833 This is a reproduction of the or...
4463,9781406922905,1406922900,"The Pronouncing Reading Book for Children, Wit...",William L Robinson,History,http://books.google.com/books/content?id=gyiJy...,This is a reproduction of the original artefac...,2019.0,3.66,92.0,2477.0,"The Pronouncing Reading Book for Children, Wit...",9781406922905 This is a reproduction of the or...
4464,9781406934854,1406934852,A Commentary Upon the Gospel According to S. Luke,Saint Cyril (patriarch of Alexandria),History,http://books.google.com/books/content?id=Mclsy...,This is a reproduction of the original artefac...,2019.0,3.59,362.0,669.0,A Commentary Upon the Gospel According to S. Luke,9781406934854 This is a reproduction of the or...
4466,9781406957242,1406957240,The Story of the Life of Lafayette,Mrs John Farrar,History,http://books.google.com/books/content?id=oVd-y...,This is a reproduction of the original artefac...,2019.0,3.93,368.0,29.0,The Story of the Life of Lafayette: As Told by...,9781406957242 This is a reproduction of the or...
4700,9781573226882,1573226882,Fever Pitch,Nick Hornby,Biography & Autobiography,http://books.google.com/books/content?id=v5TO8...,An autobiographical memoir by a humorous Briti...,1998.0,3.73,247.0,27781.0,Fever Pitch,9781573226882 An autobiographical memoir by a ...